---
title: "About This Site"
output: 
  html_document
---

<div style="margin-bottom: 30px;"></div>

This personal website was created as part of my academic coursework to showcase my information and project in my homework.

<div style="margin-bottom: 30px;"></div>

<strong>Site Details:</strong>

Built with R Markdown for content creation; HTML/CSS for styling and layout; GitHub Pages for hosting

Source Code: The complete source code for this website is available on GitHub.

This site includes: Personal Website (A brief introductory landing page | resume | Navigation links) and Interactive Dashboard (Problem 2)

<div style="margin-bottom: 30px;"></div>

<strong>Site Structure:</strong>

Home: Introduction and overview

About: This page - technical details about the site

Resume: Academic and professional experience

Projects: Data science projects and interactive visualizations

<div style="margin-bottom: 30px;"></div>

<strong>Contact</strong>

For questions about this website or my work, please feel free to email me.